version: '3'
services:
  database:
    image: postgres:latest
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - ./init-scripts/inserts.sql:/docker-entrypoint-initdb.d/inserts.sql
    ports:
      - "5432:5432"
    networks:
      - default
  backend:
    environment:
        POSTGRES_USER: ${POSTGRES_USER}
        POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
        POSTGRES_PORT: ${POSTGRES_PORT}
        POSTGRES_DB: ${POSTGRES_DB}
    build:
      context: ./backend
    ports:
      - "3000:3000"
    depends_on:
      - database
    networks:
      - default
  frontend:
    environment:
        API_URL: ${API_URL}
    build:
      context: ./client
    ports:
      - "8080:80"
    networks:
      - default